version: '2'
services:
    ptc00demo-app:
        image: ptc00demo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://ptc00demo-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ptc00demo-mssql:
        extends:
            file: mssql.yml
            service: ptc00demo-mssql
